version: '3'

services:
  zipkin:
    image: openzipkin/zipkin
    environment:
      - STORAGE_TYPE=mysql
      - MYSQL_HOST=db
    depends_on:
      - db
    ports:
      - 9411:9411
  db:
    image: openzipkin/zipkin-mysql
    container_name: mysql
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/usr/src/app
    hostname: frontend
    ports:
      - "8001:8000"
    command: "python manage.py runserver frontend:8000"


  dependencies:
    image: openzipkin/zipkin-dependencies
    container_name: dependencies
    entrypoint: crond -f
    environment:
      - STORAGE_TYPE=mysql
      - MYSQL_HOST=db
      - MYSQL_USER=zipkin
      - MYSQL_PASS=zipkin
      - JAVA_OPTS=-verbose:gc -Xms512m -Xmx512m
    depends_on:
      - db
    restart: unless-stopped

